### ISSUE TITLE
Is 'tickets' down?

### ISSUE THREAD

**Issue by hewr1993** [protream/iquery#16]
> \# iquery 北京西 广州南 713
> /usr/lib/python3/dist-packages/urllib3/connectionpool.py:732: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html (This warning will only appear once by default.)
>   InsecureRequestWarning)
> Sorry, server is not responding.

Is this just me?

**Comment by yeyuguo** [comment]
yes,you are a lucky boy
